version: "3"
services:
  locator:
    image: apachegeode/geode
    container_name: geodelocator
    hostname: geodelocator
    cpu_count: 1
    mem_limit: 512m
    ports:
      - "10334:10334"
      - "1099:1099"
      - "7070:7070"
      - "40404:40404"
    command: sh -c "gfsh start locator --name=locator-`hostname` && tail -f /locator-`hostname`/locator-`hostname`.log"
  server:
    image: apachegeode/geode
    cpu_count: 2
    mem_limit: 1g
    depends_on:
      - locator
    links:
      - locator
    command: >
      bash -c 'until gfsh start server --name=server-`hostname` --bind-address=`hostname -i` --locators=geodelocator[10334];\
               do \
                 sleep 3; \
               done && \
               tail -f /server-`hostname`/server-`hostname`.log'