server:
  port: 7070
  error:
    includeStacktrace: always
spring:
  application:
    name: orchestration-service
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true
      FAIL_ON_EMPTY_BEANS: false
      write-dates-as-timestamps: false
  sleuth:
    async:
      enabled: true
    enabled: true
    reactor:
      enabled: true
    sampler:
      probability: 1
  reactor:
    debug-agent:
      enabled: true
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/eventuate
    username: eventuate
    password: eventuate
    name: eventuate

eventuate:
  reactive:
    db:
      driver: postgres
      host: localhost
      port: 5432
      username: eventuate
      password: eventuate
      database: eventuate



cdc.service.url: http://localhost:8099
eventuatelocal.kafka.bootstrap.servers: ${DOCKER_HOST_IP:localhost}:9092
eventuatelocal.zookeeper.connection.string: ${DOCKER_HOST_IP:localhost}:2181
eventuate.outbox.id: 1

info:
  name: ${spring.application.name}
  environment: ${spring.profiles.active}
  version: 0.0.1

logging:
  level:
    root: info
    org.apache.kafka: info
    org.springframework.cloud.stream: warn
    org.springframework.integration: warn