apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: kafka-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka-cluster
  project: route-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  source:
    repoURL: 'https://gitlab.com/route-project/deploy-config.git'
    path: kubernetes/kafka
    targetRevision: HEAD
    helm:
      parameters:
        - name: replicaCount
          value: '3'
        - name: numPartitions
          value: '8'
        - name: defaultReplicationFactor
          value: '2'