apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: kafka-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kafka-cluster
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/kafka
    repoURL: 'https://gitlab.com/route-project/deploy-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: kafka-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
