apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: kafka-cluster-space
spec:
  destination:
    name: ''
    namespace: kafka-cluster-space
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/kafka
    repoURL: 'https://gitlab.com/route-project/deploy-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: kafka-cluster-space
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
