---
version: '2'

services:

  postgres:
    image: eventuateio/eventuate-postgres:0.15.0.BUILD-SNAPSHOT
    ports:
      - 5432:5432
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate
      USE_DB_ID: "false"
      USE_JSON_PAYLOAD_AND_HEADERS: "true"

  cdc-service:
    image: eventuateio/eventuate-cdc-service:latest
    ports:
      - "8099:8080"
    depends_on:
      - postgres
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: localhost:19092,localhost:29092,localhost:39092,localhost:19072,localhost:29072,localhost:39072
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: localhost:22181
      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader2
      EVENTUATE_CDC_READER_READER2_TYPE: postgres-wal
      eventuate.cdc.reader.reader2.outboxId: 1
      EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:postgresql://postgres/eventuate
      EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: eventuate
      EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: eventuate
      EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/eventuatetram
      EVENTUATE_CDC_READER_READER2_OFFSETSTORAGETOPICNAME: db.history.eventuate.tram

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    image: confluentinc/cp-enterprise-kafka:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: rack-a
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:19092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: localhost:22181
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=9997
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-2:
    image: confluentinc/cp-enterprise-kafka:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: rack-a
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: localhost:22181
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-3:
    image: confluentinc/cp-enterprise-kafka:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_RACK: rack-a
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:39092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: localhost:22181
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-4:
    image: confluentinc/cp-enterprise-kafka:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_BROKER_RACK: rack-b
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19072
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:19072
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: localhost:22181
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-5:
    image: confluentinc/cp-enterprise-kafka:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_BROKER_RACK: rack-b
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29072
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:29072
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: localhost:22181
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-6:
    image: confluentinc/cp-enterprise-kafka:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 6
      KAFKA_BROKER_RACK: rack-b
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39072
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:39072
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: localhost:22181
    extra_hosts:
      - "moby:127.0.0.1"

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017

  consul:
    image: docker.io/bitnami/consul:1
    volumes:
      - /home/data:/bitnami/consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'