server:
  port: 2020
  error:
    includeStacktrace: always
spring:
  application:
    name: route-service
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true
      FAIL_ON_EMPTY_BEANS: false
      write-dates-as-timestamps: false
  sleuth:
    async:
      enabled: true
    enabled: true
    reactor:
      enabled: true
    sampler:
      probability: 1
  reactor:
    debug-agent:
      enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/eventuate
    username: eventuate
    password: eventuate
    name: eventuate
  couchbase:
    connection-string: "127.0.0.1"
    username: test
    password: testtest
  data:
    couchbase:
      auto-index: true
      bucket-name: route-bucket



eventuate.reactive.db.driver: postgres
eventuate.reactive.db.host: localhost
eventuate.reactive.db.port: 5432
eventuate.reactive.db.username: eventuate
eventuate.reactive.db.password: eventuate
eventuate.reactive.db.database: eventuate



cdc.service.url: http://localhost:8099
eventuatelocal.kafka.bootstrap.servers: ${DOCKER_HOST_IP:localhost}:9092
eventuatelocal.zookeeper.connection.string: ${DOCKER_HOST_IP:localhost}:2181
eventuate.outbox.id: 1



info:
  name: ${spring.application.name}
  environment: ${spring.profiles.active}
  version: 0.0.1

logging:
  level:
    root: info
    org.apache.kafka: info
    org.springframework.cloud.stream: warn
    org.springframework.integration: warn